In [134]:
import pandas as pd
import numpy as np
BPSO = pd.read_csv("Dataset2_BPSO.txt", index_col=False)
BPSO_OBL = pd.read_csv("Dataset2_BPSO+OBL.txt", index_col=False)
SFS = pd.read_csv("Dataset2_SFS.txt", index_col=False)
Results = pd.DataFrame()
Results2= pd.DataFrame()

In [135]:
Results['BPSO']= BPSO['Train Score']
Results['BPSO_OBL']=BPSO_OBL['Train Score']
Results['SFS'] = SFS['Train Score']

In [136]:
Results2['BPSO_2']= BPSO['Test Score']
Results2['BPSO_OBL_2']=BPSO_OBL['Test Score']
Results2['SFS_2'] = SFS['Test Score']

In [137]:
Results

       BPSO  BPSO_OBL       SFS
0  0.843373  0.837349  0.849398
1  0.837349  0.831325  0.819277
2  0.813253  0.807229  0.807229
3  0.867470  0.855422  0.825301
4  0.879518  0.843373  0.879518
5  0.813253  0.813253  0.837349
6  0.837349  0.825301  0.843373
7  0.861446  0.849398  0.885542
8  0.843373  0.861446  0.819277
9  0.843373  0.813253  0.825301

In [138]:
Results2

     BPSO_2  BPSO_OBL_2     SFS_2
0  0.785714    0.761905  0.809524
1  0.880952    0.833333  0.785714
2  0.928571    0.880952  0.857143
3  0.714286    0.785714  0.690476
4  0.738095    0.809524  0.714286
5  0.928571    0.880952  0.833333
6  0.857143    0.833333  0.809524
7  0.642857    0.690476  0.523810
8  0.809524    0.738095  0.666667
9  0.833333    0.738095  0.809524

In [139]:
Results = pd.melt(Results,var_name='Type', value_name='Train_Score')
Results = Results.reset_index(drop=True)

Results2 = pd.melt(Results2,var_name='Type', value_name='Test_Score')
Results2 = Results2.reset_index(drop=True)

In [140]:
Results

        Type  Train_Score
0       BPSO     0.843373
1       BPSO     0.837349
2       BPSO     0.813253
3       BPSO     0.867470
4       BPSO     0.879518
5       BPSO     0.813253
6       BPSO     0.837349
7       BPSO     0.861446
8       BPSO     0.843373
9       BPSO     0.843373
10  BPSO_OBL     0.837349
11  BPSO_OBL     0.831325
12  BPSO_OBL     0.807229
13  BPSO_OBL     0.855422
14  BPSO_OBL     0.843373
15  BPSO_OBL     0.813253
16  BPSO_OBL     0.825301
17  BPSO_OBL     0.849398
18  BPSO_OBL     0.861446
19  BPSO_OBL     0.813253
20       SFS     0.849398
21       SFS     0.819277
22       SFS     0.807229
23       SFS     0.825301
24       SFS     0.879518
25       SFS     0.837349
26       SFS     0.843373
27       SFS     0.885542
28       SFS     0.819277
29       SFS     0.825301

In [141]:
Results2

          Type  Test_Score
0       BPSO_2    0.785714
1       BPSO_2    0.880952
2       BPSO_2    0.928571
3       BPSO_2    0.714286
4       BPSO_2    0.738095
5       BPSO_2    0.928571
6       BPSO_2    0.857143
7       BPSO_2    0.642857
8       BPSO_2    0.809524
9       BPSO_2    0.833333
10  BPSO_OBL_2    0.761905
11  BPSO_OBL_2    0.833333
12  BPSO_OBL_2    0.880952
13  BPSO_OBL_2    0.785714
14  BPSO_OBL_2    0.809524
15  BPSO_OBL_2    0.880952
16  BPSO_OBL_2    0.833333
17  BPSO_OBL_2    0.690476
18  BPSO_OBL_2    0.738095
19  BPSO_OBL_2    0.738095
20       SFS_2    0.809524
21       SFS_2    0.785714
22       SFS_2    0.857143
23       SFS_2    0.690476
24       SFS_2    0.714286
25       SFS_2    0.833333
26       SFS_2    0.809524
27       SFS_2    0.523810
28       SFS_2    0.666667
29       SFS_2    0.809524

In [142]:
Results['Type']= Results['Type'].astype('category')
Results2['Type']= Results2['Type'].astype('category')

In [143]:
import matplotlib.pyplot as plt
import seaborn
%matplotlib inline

In [144]:
#Train Score
import statsmodels.formula.api as smf
import statsmodels.stats.multicomp as multi 

model1= smf.ols('Train_Score ~ C(Type)', data=Results)
results= model1.fit()
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:            Train_Score   R-squared:                       0.038
Model:                            OLS   Adj. R-squared:                 -0.034
Method:                 Least Squares   F-statistic:                    0.5287
Date:                Sat, 08 Jun 2019   Prob (F-statistic):              0.595
Time:                        20:02:29   Log-Likelihood:                 73.131
No. Observations:                  30   AIC:                            -140.3
Df Residuals:                      27   BIC:                            -136.1
Df Model:                           2
Covariance Type:            nonrobust
=======================================================================================
                          coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------
Intercept               0.8440      0.007    119.776      0.000       0.830       0.858
C(Type)[T.BPSO_OBL]    -0.0102      0.010     -1.028      0.313      -0.031       0.010
C(Type)[T.SFS]         -0.0048      0.010     -0.484      0.633      -0.025       0.016
==============================================================================
Omnibus:                        1.446   Durbin-Watson:                   2.243
Prob(Omnibus):                  0.485   Jarque-Bera (JB):                1.348
Skew:                           0.415   Prob(JB):                        0.510
Kurtosis:                       2.375   Cond. No.                         3.73
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [145]:
mc1 = multi.MultiComparison(Results['Train_Score'], Results['Type'])
res1 = mc1.tukeyhsd()
print(res1.summary())

Multiple Comparison of Means - Tukey HSD,FWER=0.05
================================================
 group1   group2  meandiff  lower  upper  reject
------------------------------------------------
  BPSO   BPSO_OBL -0.0102  -0.0349 0.0145 False
  BPSO     SFS    -0.0048  -0.0295 0.0199 False
BPSO_OBL   SFS     0.0054  -0.0193 0.0301 False
------------------------------------------------

In [147]:
#Test Scores
import statsmodels.formula.api as smf
import statsmodels.stats.multicomp as multi 

model1= smf.ols('Test_Score ~ C(Type)', data=Results2)
results= model1.fit()
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:             Test_Score   R-squared:                       0.090
Model:                            OLS   Adj. R-squared:                  0.022
Method:                 Least Squares   F-statistic:                     1.329
Date:                Sat, 08 Jun 2019   Prob (F-statistic):              0.282
Time:                        20:04:24   Log-Likelihood:                 31.967
No. Observations:                  30   AIC:                            -57.93
Df Residuals:                      27   BIC:                            -53.73
Df Model:                           2
Covariance Type:            nonrobust
=========================================================================================
                            coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------
Intercept                 0.8119      0.028     29.217      0.000       0.755       0.869
C(Type)[T.BPSO_OBL_2]    -0.0167      0.039     -0.424      0.675      -0.097       0.064
C(Type)[T.SFS_2]         -0.0619      0.039     -1.575      0.127      -0.143       0.019
==============================================================================
Omnibus:                        3.640   Durbin-Watson:                   1.958
Prob(Omnibus):                  0.162   Jarque-Bera (JB):                2.674
Skew:                          -0.730   Prob(JB):                        0.263
Kurtosis:                       3.098   Cond. No.                         3.73
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [149]:
mc1 = multi.MultiComparison(Results2['Test_Score'], Results2['Type'])
res1 = mc1.tukeyhsd()
print(res1.summary())

 Multiple Comparison of Means - Tukey HSD,FWER=0.05
====================================================
  group1     group2   meandiff  lower  upper  reject
----------------------------------------------------
  BPSO_2   BPSO_OBL_2 -0.0167  -0.1141 0.0808 False
  BPSO_2     SFS_2    -0.0619  -0.1593 0.0355 False
BPSO_OBL_2   SFS_2    -0.0452  -0.1427 0.0522 False
----------------------------------------------------

In [150]:
from scipy import stats
t_value, p_value = stats.ttest_ind(group2, group1)

In [151]:
t_value

-1.136706356664587

In [152]:
from scipy import stats
t_value2, p_value2 = stats.ttest_ind(group2, group3)

In [153]:
t_value2

-0.5331139899832051

In [154]:
from scipy import stats
t_value3, p_value3 = stats.ttest_ind(group1, group3)

In [155]:
t_value3

0.45274960674270986